### ISSUE TITLE
Elasticsearch is not starting and getting error

### ISSUE THREAD

**Issue by cinetube** [bbilly1/tubearchivist#100]
Elasticsearch container is not starting. Please check the attached screenshot. 

![Screenshot 2021-12-05 232028](https://user-images.githubusercontent.com/23441775/144756704-9e586755-a973-4184-b4ac-c65380a32e32.jpg)

Here is my docker compose file - 

```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    ports:
      - 8010:8000
    volumes:
      - ./volumes/tubearchivist/media:/youtube
      - ./volumes/tubearchivist/cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=tubearchivist
      - TA_PASSWORD=verysecret
      - ELASTIC_PASSWORD=verysecret
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./volumes/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=verysecret"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/tubearchivist/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
  ```

Please guide me what changes I need to make in the docker-compose file to make Tube Archivist run properly.
